"""
Central module that imports and re-exports all models for easier imports.
"""

# Base models
from .base import (
    BaseModel,
    BaseNamedModel,
    BaseSoftDeleteModel,
    BaseUserOwnedModel,
    BaseCourseModel,
    BaseUserCourseModel,
    BasePublishableModel,
    BaseOrderedModel,
    BaseContentModel,
    BaseCommentModel,
    BaseVersionedModel,
    BaseAttachmentModel,
    BaseSettingsModel,
    TimestampMixin,
    SoftDeleteMixin,
)

# Core models
from .user import User, UserRole, User_Pydantic, UserCreate_Pydantic, UserUpdate_Pydantic

from .course import (
    Course,
    Section,
    CourseVisibility,
    CourseState,
    GradingScheme,
    Course_Pydantic,
    CourseCreate_Pydantic,
    Section_Pydantic,
    SectionCreate_Pydantic,
)

from .enrollment import (
    Enrollment,
    EnrollmentType,
    EnrollmentState,
    Enrollment_Pydantic,
    EnrollmentCreate_Pydantic,
    EnrollmentUpdate_Pydantic,
)

from .assignment import (
    Assignment,
    AssignmentGroup,
    Rubric,
    RubricCriterion,
    RubricRating,
    AssignmentType,
    SubmissionType,
    GradingType,
    Assignment_Pydantic,
    AssignmentCreate_Pydantic,
    AssignmentGroup_Pydantic,
    Rubric_Pydantic,
)

from .submission import (
    Submission,
    SubmissionAttachment,
    Grade,
    Comment,
    SubmissionStatus,
    Submission_Pydantic,
    SubmissionCreate_Pydantic,
    Grade_Pydantic,
    GradeCreate_Pydantic,
    Comment_Pydantic,
    SubmissionAttachment_Pydantic,
)

from .grade import (
    GradeBook,
    GradeEntry,
    GradingSchemeTemplate,
    GradingCurve,
    GradeStatusEnum,
    GradeSource,
    GradeBook_Pydantic,
    GradeBookCreate_Pydantic,
    GradeEntry_Pydantic,
    GradeEntryCreate_Pydantic,
    GradingSchemeTemplate_Pydantic,
    GradingCurve_Pydantic,
)

from .discussion import (
    DiscussionForum,
    DiscussionTopic,
    DiscussionReply,
    DiscussionReplyLike,
    DiscussionTopicSubscription,
    DiscussionVisibility,
    DiscussionType,
    DiscussionForum_Pydantic,
    DiscussionForumCreate_Pydantic,
    DiscussionTopic_Pydantic,
    DiscussionTopicCreate_Pydantic,
    DiscussionReply_Pydantic,
    DiscussionReplyCreate_Pydantic,
)

from .calendar import (
    CalendarEvent,
    CalendarEventAttendee,
    CalendarSubscription,
    EventReminder,
    EventType,
    RecurrenceType,
    CalendarEvent_Pydantic,
    CalendarEventCreate_Pydantic,
    CalendarEventAttendee_Pydantic,
    CalendarSubscription_Pydantic,
    EventReminder_Pydantic,
)

from .notification import (
    Notification,
    UserNotification,
    NotificationPreference,
    NotificationBatch,
    NotificationType,
    NotificationPriority,
    NotificationChannel,
    Notification_Pydantic,
    NotificationCreate_Pydantic,
    UserNotification_Pydantic,
    NotificationPreference_Pydantic,
    NotificationBatch_Pydantic,
)

from .file import (
    File,
    Folder,
    FileFolder,
    FileVersion,
    FilePermission,
    FileUsage,
    FileType,
    FileStatus,
    StorageProvider,
    File_Pydantic,
    FileCreate_Pydantic,
    Folder_Pydantic,
    FolderCreate_Pydantic,
    FileVersion_Pydantic,
    FilePermission_Pydantic,
)

from .module import (
    Module,
    ModuleItem,
    ModuleCompletion,
    ModuleItemCompletion,
    ModuleType,
    CompletionRequirement,
    Module_Pydantic,
    ModuleCreate_Pydantic,
    ModuleItem_Pydantic,
    ModuleItemCreate_Pydantic,
    ModuleCompletion_Pydantic,
    ModuleItemCompletion_Pydantic,
)

from .quiz import (
    Quiz,
    Question,
    QuestionAnswer,
    QuizQuestion,
    QuizQuestionGroup,
    QuizAttempt,
    QuizResponse,
    QuestionBank,
    QuizType,
    QuestionType,
    Quiz_Pydantic,
    QuizCreate_Pydantic,
    Question_Pydantic,
    QuizAttempt_Pydantic,
    QuizResponse_Pydantic,
)

from .group import (
    Group,
    GroupSet,
    GroupMembership,
    GroupAssignment,
    GroupCategory,
    PeerReview,
    GroupInvitation,
    GroupType,
    Group_Pydantic,
    GroupCreate_Pydantic,
    GroupSet_Pydantic,
    GroupMembership_Pydantic,
    GroupAssignment_Pydantic,
    PeerReview_Pydantic,
)

from .announcement import (
    Announcement,
    AnnouncementComment,
    AnnouncementLike,
    AnnouncementAttachment,
    AnnouncementRead,
    AnnouncementRecipient,
    AnnouncementRecipientType,
    AnnouncementPriority,
    Announcement_Pydantic,
    AnnouncementCreate_Pydantic,
    AnnouncementComment_Pydantic,
    AnnouncementLike_Pydantic,
    AnnouncementRead_Pydantic,
)

# Create a list of all models for Tortoise ORM registration
MODELS = [
    # User
    User,
    
    # Course
    Course,
    Section,
    
    # Enrollment
    Enrollment,
    
    # Assignment
    Assignment,
    AssignmentGroup,
    Rubric,
    RubricCriterion,
    RubricRating,
    
    # Submission
    Submission,
    SubmissionAttachment,
    Grade,
    Comment,
    
    # Grade
    GradeBook,
    GradeEntry,
    GradingSchemeTemplate,
    GradingCurve,
    
    # Discussion
    DiscussionForum,
    DiscussionTopic,
    DiscussionReply,
    DiscussionReplyLike,
    DiscussionTopicSubscription,
    
    # Calendar
    CalendarEvent,
    CalendarEventAttendee,
    CalendarSubscription,
    EventReminder,
    
    # Notification
    Notification,
    UserNotification,
    NotificationPreference,
    NotificationBatch,
    
    # File
    File,
    Folder,
    FileFolder,
    FileVersion,
    FilePermission,
    FileUsage,
    
    # Module
    Module,
    ModuleItem,
    ModuleCompletion,
    ModuleItemCompletion,
    
    # Quiz
    Quiz,
    Question,
    QuestionAnswer,
    QuizQuestion,
    QuizQuestionGroup,
    QuizAttempt,
    QuizResponse,
    QuestionBank,
    
    # Group
    Group,
    GroupSet,
    GroupMembership,
    GroupAssignment,
    GroupCategory,
    PeerReview,
    GroupInvitation,
    
    # Announcement
    Announcement,
    AnnouncementComment,
    AnnouncementLike,
    AnnouncementAttachment,
    AnnouncementRead,
    AnnouncementRecipient,
]

# For easy import in your application
__all__ = [
    # Base models
    'BaseModel',
    'BaseNamedModel',
    'BaseSoftDeleteModel',
    'BaseUserOwnedModel',
    'BaseCourseModel',
    'BaseUserCourseModel',
    'BasePublishableModel',
    'BaseOrderedModel',
    'BaseContentModel',
    'BaseCommentModel',
    'BaseVersionedModel',
    'BaseAttachmentModel',
    'BaseSettingsModel',
    'TimestampMixin',
    'SoftDeleteMixin',
    
    # Models
    'User',
    'Course',
    'Section',
    'Enrollment',
    'Assignment',
    'AssignmentGroup',
    'Rubric',
    'RubricCriterion',
    'RubricRating',
    'Submission',
    'SubmissionAttachment',
    'Grade',
    'Comment',
    'GradeBook',
    'GradeEntry',
    'GradingSchemeTemplate',
    'GradingCurve',
    'DiscussionForum',
    'DiscussionTopic',
    'DiscussionReply',
    'DiscussionReplyLike',
    'DiscussionTopicSubscription',
    'CalendarEvent',
    'CalendarEventAttendee',
    'CalendarSubscription',
    'EventReminder',
    'Notification',
    'UserNotification',
    'NotificationPreference',
    'NotificationBatch',
    'File',
    'Folder',
    'FileFolder',
    'FileVersion',
    'FilePermission',
    'FileUsage',
    'Module',
    'ModuleItem',
    'ModuleCompletion',
    'ModuleItemCompletion',
    'Quiz',
    'Question',
    'QuestionAnswer',
    'QuizQuestion',
    'QuizQuestionGroup',
    'QuizAttempt',
    'QuizResponse',
    'QuestionBank',
    'Group',
    'GroupSet',
    'GroupMembership',
    'GroupAssignment',
    'GroupCategory',
    'PeerReview',
    'GroupInvitation',
    'Announcement',
    'AnnouncementComment',
    'AnnouncementLike',
    'AnnouncementAttachment',
    'AnnouncementRead',
    'AnnouncementRecipient',
    
    # Enums
    'UserRole',
    'CourseVisibility',
    'CourseState',
    'GradingScheme',
    'EnrollmentType',
    'EnrollmentState',
    'AssignmentType',
    'SubmissionType',
    'GradingType',
    'SubmissionStatus',
    'GradeStatusEnum',
    'GradeSource',
    'DiscussionVisibility',
    'DiscussionType',
    'EventType',
    'RecurrenceType',
    'NotificationType',
    'NotificationPriority',
    'NotificationChannel',
    'FileType',
    'FileStatus',
    'StorageProvider',
    'ModuleType',
    'CompletionRequirement',
    'QuizType',
    'QuestionType',
    'GroupType',
    'AnnouncementRecipientType',
    'AnnouncementPriority',
    
    # Pydantic models
    'User_Pydantic',
    'UserCreate_Pydantic',
    'UserUpdate_Pydantic',
    'Course_Pydantic',
    'CourseCreate_Pydantic',
    'Section_Pydantic',
    'SectionCreate_Pydantic',
    'Enrollment_Pydantic',
    'EnrollmentCreate_Pydantic',
    'EnrollmentUpdate_Pydantic',
    'Assignment_Pydantic',
    'AssignmentCreate_Pydantic',
    'AssignmentGroup_Pydantic',
    'Rubric_Pydantic',
    'Submission_Pydantic',
    'SubmissionCreate_Pydantic',
    'Grade_Pydantic',
    'GradeCreate_Pydantic',
    'Comment_Pydantic',
    'SubmissionAttachment_Pydantic',
    'GradeBook_Pydantic',
    'GradeBookCreate_Pydantic',
    'GradeEntry_Pydantic',
    'GradeEntryCreate_Pydantic',
    'GradingSchemeTemplate_Pydantic',
    'GradingCurve_Pydantic',
    'DiscussionForum_Pydantic',
    'DiscussionForumCreate_Pydantic',
    'DiscussionTopic_Pydantic',
    'DiscussionTopicCreate_Pydantic',
    'DiscussionReply_Pydantic',
    'DiscussionReplyCreate_Pydantic',
    'CalendarEvent_Pydantic',
    'CalendarEventCreate_Pydantic',
    'CalendarEventAttendee_Pydantic',
    'CalendarSubscription_Pydantic',
    'EventReminder_Pydantic',
    'Notification_Pydantic',
    'NotificationCreate_Pydantic',
    'UserNotification_Pydantic',
    'NotificationPreference_Pydantic',
    'NotificationBatch_Pydantic',
    'File_Pydantic',
    'FileCreate_Pydantic',
    'Folder_Pydantic',
    'FolderCreate_Pydantic',
    'FileVersion_Pydantic',
    'FilePermission_Pydantic',
    'Module_Pydantic',
    'ModuleCreate_Pydantic',
    'ModuleItem_Pydantic',
    'ModuleItemCreate_Pydantic',
    'ModuleCompletion_Pydantic',
    'ModuleItemCompletion_Pydantic',
    'Quiz_Pydantic',
    'QuizCreate_Pydantic',
    'Question_Pydantic',
    'QuizAttempt_Pydantic',
    'QuizResponse_Pydantic',
    'Group_Pydantic',
    'GroupCreate_Pydantic',
    'GroupSet_Pydantic',
    'GroupMembership_Pydantic',
    'GroupAssignment_Pydantic',
    'PeerReview_Pydantic',
    'Announcement_Pydantic',
    'AnnouncementCreate_Pydantic',
    'AnnouncementComment_Pydantic',
    'AnnouncementLike_Pydantic',
    'AnnouncementRead_Pydantic',
    
    # Model list for registration
    'MODELS',
]